{% set name = "cel-python" %}
{% set version = "0.5.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/cloud-custodian/{{ name }}/archive/refs/tags/v{{ version[:-2] }}.tar.gz
  sha256: b370b2494e838a05e9a0d3bdabe045640fb2cc46c4fb9d853cb0559f513eeed9

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<310]

requirements:
  host:
    - python
    - pip
    - hatchling
  run:
    - python
    - google-re2 >=1.1.20240702
    - google-re2 >=1.1.20250722  # [py==313]
    - jmespath >=1.0.1
    - lark >=1.2.2
    - pendulum >=3.1.0
    - pyyaml >=6.0.2
    - tomli >=1.1.0  # [py<311]


{% set deselect_tests = "" %}
# AttributeError: module 'os' has n...
{% set deselect_tests = deselect_tests + " --deselect=tests/test_main.py::test_stat_good" %}  # [win]

test:
  imports:
    - celpy
  source_files:
    - tests/
  requires:
    - pip
    - pytest
  commands:
    - pip check
    # Skip test_c7n_to_cel.py - ModuleNotFoundError: xlate
    - pytest -v --ignore=tests/test_c7n_to_cel.py tests/ # [py<312]
    # For python >=3.12 skip test with: TypeError: can't subtract offset-naive and offset-aware datetimes
    # This is an implementation issue for these python versions.
    - pytest -vv {{ deselect_tests }} --ignore=tests/test_c7n_to_cel.py -k "not test_extended_timestamp_type" tests/ # [py>=312]

about:
  home: https://github.com/cloud-custodian/cel-python
  summary: Pure Python implementation of the Common Expression Language
  description: |
    Pure Python implementation of Google Common Expression Language,
    https://opensource.google/projects/cel.
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  dev_url: https://github.com/cloud-custodian/cel-python
  doc_url: https://cloud-custodian.github.io/cel-python/build/html/index.html
